### ISSUE TITLE
"The gardener's magazine and register of rural & domestic improvement" doesn't appear among the periodicals in Recents; the  classified pages are not counted in the personal stats

### ISSUE THREAD

**Issue by yshish** [zooniverse/BHL#38]
The periodical *The gardener's magazine and register of rural & domestic improvement* doesn't appear among the periodicals in my Recents, moreover, the pages I classify are not counted in my personal stats. All the other periodicals do get counted and do display there without any problems.

Jules has just tested it herself with the same results.

The count of completed pages on the http://www.sciencegossip.org/#/periodicals has just jumped from 609 to 610 for this periodical, which means the classifications probably do get recorded.

Please, could anyone look at this? Thanks!

**Comment by eatyourgreens** [comment]
I've just classified http://talk.sciencegossip.org/#/subjects/ASC0002toh on my account. It shows up in my Recents, and the count went up on my profile page. Still there when I reloaded the page, so it has updated on the backend too. I'm not sure what's going on with your and Jules' accounts.

**Comment by yshish** [comment]
Odd. I made a screenshot of my Recents where all the periodicals (except the Gardener's) are displayed and listed the page with a visible title of the Gardener's. I hovered over it with the cursor so we can check the ID number (bottom left corner). Can you tell whether my classification of this particular page has been recorded?

![](https://lh3.googleusercontent.com/-W-u3BgG9IzE/VcJuPERzXDI/AAAAAAAAIRg/TJPUpBmJUIE/s0-Ic42/ysh_2015-08-05.jpg)

**Comment by parrish** [comment]
Wow! That was one of the strangest bugs I think I've encountered, but it's fixed now.

@eatyourgreens it looks like a a/b split was introduced without a key -- which apparently breaks updates to the project counters.

I went ahead and fixed the counters as well

**Comment by yshish** [comment]
Awesome! :) Thanks. I can see them displayed in the Recents now. Actually, the stats/ribbon don't show them yet and neither any classifications I have done in the other periodicals since reporting this bug. Is there a delay?

**Comment by parrish** [comment]
Ah.  Good call, that is related -- I'll have to get all the other users sorted out as well to get that working again

**Comment by parrish** [comment]
After your next classification, it should update the stats ribbon.

**Comment by yshish** [comment]
Working :)
