### ISSUE TITLE
The symbol for Original page is redirecting to the main project page instead of the BHL document

### ISSUE THREAD

**Issue by yshish** [zooniverse/BHL#43]
When you click on the icon for displaying the original page on the Classification page, it is redirecting you to http://www.sciencegossip.org/ instead of to the BHL document.

http://talk.sciencegossip.org/#/boards/BSC0000006/discussions/DSC000054u?page=1&comment_id=5662475296ad6f091b0011f4

**Comment by eatyourgreens** [comment]
Fixed by b8f974b3ad5d8439022b3a0888483450ccbff1d2
